service: lambda-test

useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    # auto import all env vars because of serverless-dotenv-plugin

functions:
  api:
    handler: dist/lambda.handler
    events:
      #- http:
      #    method: ANY
      #    path: /
      #- http:
      #    method: ANY
      #    path: '{proxy+}'
      #- http:
      #    method: ANY
      #    path: /{any+}
    - http:
        method: any
        path: '/'
    - http:
        method: any
        path: '/{proxy+}'

custom:
  # serverless offline plugin setup
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true

